-- -------------
-- CATEGORIES --
-- -------------

INSERT INTO category (name) VALUES ('Cardguard');
INSERT INTO category (name) VALUES ('Viva');
INSERT INTO category (name) VALUES ('Span');
INSERT INTO category (name) VALUES ('Wrapsafe');
INSERT INTO category (name) VALUES ('Sonair');
INSERT INTO category (name) VALUES ('Bytecard');
INSERT INTO category (name) VALUES ('Subin');
INSERT INTO category (name) VALUES ('Regrant');
INSERT INTO category (name) VALUES ('Flexidy');
INSERT INTO category (name) VALUES ('Prodder');

-- ------------
-- LOCATIONS --
-- ------------

INSERT INTO location (postalCode, name) VALUES (82887, 'Badin');
INSERT INTO location (postalCode, name) VALUES (28254, 'Cau Giay');
INSERT INTO location (postalCode, name) VALUES (18105, 'Batelov');
INSERT INTO location (postalCode, name) VALUES (24186, 'Tallbisah');
INSERT INTO location (postalCode, name) VALUES (29781, 'Buenavista');
INSERT INTO location (postalCode, name) VALUES (71637, 'Laylay');
INSERT INTO location (postalCode, name) VALUES (95468, 'Gorki');
INSERT INTO location (postalCode, name) VALUES (65344, 'Jiachuan');
INSERT INTO location (postalCode, name) VALUES (61535, 'Ngurensiti');
INSERT INTO location (postalCode, name) VALUES (78546, 'Tertek');
INSERT INTO location (postalCode, name) VALUES (88852, 'Sirnasari');
INSERT INTO location (postalCode, name) VALUES (54326, 'Tungelsta');
INSERT INTO location (postalCode, name) VALUES (25855, 'San Jose de las Lajas');
INSERT INTO location (postalCode, name) VALUES (95589, 'Kuripan');
INSERT INTO location (postalCode, name) VALUES (30569, 'Hekou');
INSERT INTO location (postalCode, name) VALUES (17350, 'Yuli');
INSERT INTO location (postalCode, name) VALUES (62378, 'Norberg');
INSERT INTO location (postalCode, name) VALUES (72819, 'Nizhniye Vyazovyye');
INSERT INTO location (postalCode, name) VALUES (44360, 'Abiko');
INSERT INTO location (postalCode, name) VALUES (57913, 'Lamawan');
INSERT INTO location (postalCode, name) VALUES (73641, 'Norrköping');
INSERT INTO location (postalCode, name) VALUES (92858, 'Sanxiang');
INSERT INTO location (postalCode, name) VALUES (68914, 'Jedlnia-Letnisko');
INSERT INTO location (postalCode, name) VALUES (93680, 'Aix-en-Provence');
INSERT INTO location (postalCode, name) VALUES (41801, 'Ramenki');
INSERT INTO location (postalCode, name) VALUES (89114, 'Rivera');
INSERT INTO location (postalCode, name) VALUES (43255, 'Futian');
INSERT INTO location (postalCode, name) VALUES (60502, 'Renfengzhuang');
INSERT INTO location (postalCode, name) VALUES (28373, 'Qiying');
INSERT INTO location (postalCode, name) VALUES (73213, 'Fushe-Bulqize');
INSERT INTO location (postalCode, name) VALUES (78669, 'Rantau');
INSERT INTO location (postalCode, name) VALUES (79580, 'Al Humaydat');
INSERT INTO location (postalCode, name) VALUES (11044, 'San Francisco');
INSERT INTO location (postalCode, name) VALUES (46332, 'Pamiers');
INSERT INTO location (postalCode, name) VALUES (25425, 'Guanghai');
INSERT INTO location (postalCode, name) VALUES (80278, 'Örebro');
INSERT INTO location (postalCode, name) VALUES (53333, 'Paris 14');
INSERT INTO location (postalCode, name) VALUES (41538, 'Facatativa');
INSERT INTO location (postalCode, name) VALUES (71298, 'Grabow nad Prosna');
INSERT INTO location (postalCode, name) VALUES (79541, 'Storvik');
INSERT INTO location (postalCode, name) VALUES (52527, 'Governador Valadares');
INSERT INTO location (postalCode, name) VALUES (69361, 'Sagae');
INSERT INTO location (postalCode, name) VALUES (20614, 'Jiuhua');
INSERT INTO location (postalCode, name) VALUES (24087, 'Bogo');
INSERT INTO location (postalCode, name) VALUES (57954, 'Shache');
INSERT INTO location (postalCode, name) VALUES (79112, 'Hellevoetsluis');
INSERT INTO location (postalCode, name) VALUES (37843, 'Zhulebino');
INSERT INTO location (postalCode, name) VALUES (21835, 'Gnosjö');
INSERT INTO location (postalCode, name) VALUES (70162, 'Lam Thao');
INSERT INTO location (postalCode, name) VALUES (33186, 'Cheongsong gun');
INSERT INTO location (postalCode, name) VALUES (85457, 'Cikandang');
INSERT INTO location (postalCode, name) VALUES (77075, 'Doug An');
INSERT INTO location (postalCode, name) VALUES (81985, 'Timezgadiouine');
INSERT INTO location (postalCode, name) VALUES (94946, 'Dayton');
INSERT INTO location (postalCode, name) VALUES (93051, 'Ban Lam Luk Ka');
INSERT INTO location (postalCode, name) VALUES (79149, 'Banjar Dharmasemedi');
INSERT INTO location (postalCode, name) VALUES (82751, 'Maloarkhangelsk');
INSERT INTO location (postalCode, name) VALUES (95215, 'Vyatskiye Polyany');
INSERT INTO location (postalCode, name) VALUES (93274, 'Lexington');
INSERT INTO location (postalCode, name) VALUES (18336, 'Nürnberg');
INSERT INTO location (postalCode, name) VALUES (26370, 'Mayong');
INSERT INTO location (postalCode, name) VALUES (54251, 'Lewograran');
INSERT INTO location (postalCode, name) VALUES (69753, 'Ipora');
INSERT INTO location (postalCode, name) VALUES (11121, 'Nar-yan-Mar');
INSERT INTO location (postalCode, name) VALUES (86001, 'Getazat');
INSERT INTO location (postalCode, name) VALUES (41438, 'Nicolas Bravo');
INSERT INTO location (postalCode, name) VALUES (66403, 'Hejiabao');
INSERT INTO location (postalCode, name) VALUES (63850, 'Lusaka');
INSERT INTO location (postalCode, name) VALUES (33309, 'Tamboril');
INSERT INTO location (postalCode, name) VALUES (64447, 'Si Mahosot');
INSERT INTO location (postalCode, name) VALUES (57330, 'Qiling');
INSERT INTO location (postalCode, name) VALUES (25771, 'Lobanovo');
INSERT INTO location (postalCode, name) VALUES (98213, 'Brumado');
INSERT INTO location (postalCode, name) VALUES (92419, 'Krajanbonjor');
INSERT INTO location (postalCode, name) VALUES (33586, 'Gorzow Slaski');
INSERT INTO location (postalCode, name) VALUES (87157, 'Leuweheq');
INSERT INTO location (postalCode, name) VALUES (86611, 'Kampungruweh');
INSERT INTO location (postalCode, name) VALUES (65080, 'Tsotsin-Yurt');
INSERT INTO location (postalCode, name) VALUES (69697, 'Heichengzi');
INSERT INTO location (postalCode, name) VALUES (76613, 'Jiulong');
INSERT INTO location (postalCode, name) VALUES (85536, 'Campos Belos');
INSERT INTO location (postalCode, name) VALUES (11646, 'Iecava');
INSERT INTO location (postalCode, name) VALUES (60261, 'Ostrov');
INSERT INTO location (postalCode, name) VALUES (81727, 'Bom Jesus do Itabapoana');
INSERT INTO location (postalCode, name) VALUES (13882, 'Long’an Chengxiangzhen');
INSERT INTO location (postalCode, name) VALUES (22398, 'Uubulan');
INSERT INTO location (postalCode, name) VALUES (79235, 'Ismayilli');
INSERT INTO location (postalCode, name) VALUES (68001, 'Poniatowa');
INSERT INTO location (postalCode, name) VALUES (72192, 'Xiuyu');
INSERT INTO location (postalCode, name) VALUES (52147, 'Västeras');
INSERT INTO location (postalCode, name) VALUES (42770, 'Muhambal');
INSERT INTO location (postalCode, name) VALUES (42355, 'Esigodini');
INSERT INTO location (postalCode, name) VALUES (44408, 'Jiaokou');
INSERT INTO location (postalCode, name) VALUES (89998, 'San Jose');
INSERT INTO location (postalCode, name) VALUES (16621, 'Qingyang');
INSERT INTO location (postalCode, name) VALUES (78884, 'Cabucgayan');
INSERT INTO location (postalCode, name) VALUES (62969, 'Amnat Charoen');
INSERT INTO location (postalCode, name) VALUES (20569, 'Hluboka nad Vltavou');
INSERT INTO location (postalCode, name) VALUES (12672, 'San Pedro Apartado');
INSERT INTO location (postalCode, name) VALUES (72184, 'Yuannan');

-- ----------
-- MEMBERS --
-- ----------

insert into member (username, firstName, lastName, password, email, location) values ('akelly0', 'Aaron', 'Kelly', 'egAzhS', 'akelly0@soup.io', 19);
insert into member (username, firstName, lastName, password, email, location) values ('hford1', 'Harold', 'Ford', '0pqzDY', 'hford1@jiathis.com', 25);
insert into member (username, firstName, lastName, password, email, location) values ('jsimmons2', 'Jerry', 'Simmons', 'KljiFdaAiB2', 'jsimmons2@independent.co.uk', null);
insert into member (username, firstName, lastName, password, email, location) values ('pward3', 'Philip', 'Ward', 'BrKFZazLT', 'pward3@slashdot.org', 63);
insert into member (username, firstName, lastName, password, email, location) values ('galvarez4', 'Gary', 'Alvarez', 'NMETVHzL', 'galvarez4@amazon.de', 73);
insert into member (username, firstName, lastName, password, email, location) values ('jlittle5', 'Julie', 'Little', 'mjadFg', 'jlittle5@constantcontact.com', 61);
insert into member (username, firstName, lastName, password, email, location) values ('hpierce6', 'Howard', 'Pierce', 'DlvB9eIKXq7', 'hpierce6@printfriendly.com', 71);
insert into member (username, firstName, lastName, password, email, location) values ('phill7', 'Pamela', 'Hill', 'gtC5WqnO5a', 'phill7@amazonaws.com', 82);
insert into member (username, firstName, lastName, password, email, location) values ('bmedina8', 'Betty', 'Medina', 'PpyCdO', 'bmedina8@java.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('ejenkins9', 'Eugene', 'Jenkins', 'uDFJJA', 'ejenkins9@cargocollective.com', 56);
insert into member (username, firstName, lastName, password, email, location) values ('fyounga', 'Fred', 'Young', 'jxfLmyM', 'fyounga@cnn.com', 77);
insert into member (username, firstName, lastName, password, email, location) values ('rsimpsonb', 'Ruth', 'Simpson', 'LkOlXLYc', 'rsimpsonb@nih.gov', 18);
insert into member (username, firstName, lastName, password, email, location) values ('ggrantc', 'Gerald', 'Grant', '9szZLF6K3Fe8', 'ggrantc@cbsnews.com', 29);
insert into member (username, firstName, lastName, password, email, location) values ('bturnerd', 'Barbara', 'Turner', 'Pw8Q1y5v1Xt9', 'bturnerd@live.com', 43);
insert into member (username, firstName, lastName, password, email, location) values ('mfieldse', 'Martin', 'Fields', 'V6xG6SAQde', 'mfieldse@adobe.com', 18);
insert into member (username, firstName, lastName, password, email, location) values ('mperezf', 'Matthew', 'Perez', 'uIHkhQx9t', 'mperezf@yolasite.com', 54);
insert into member (username, firstName, lastName, password, email, location) values ('pcarpenterg', 'Philip', 'Carpenter', 'jMzWT5ZWVVI', 'pcarpenterg@bravesites.com', 53);
insert into member (username, firstName, lastName, password, email, location) values ('srossh', 'Sandra', 'Ross', 'lRaxrfM5o', 'srossh@eepurl.com', 11);
insert into member (username, firstName, lastName, password, email, location) values ('rbanksi', 'Rebecca', 'Banks', 'g35JN0G6d7', 'rbanksi@usgs.gov', 74);
insert into member (username, firstName, lastName, password, email, location) values ('amoorej', 'Anthony', 'Moore', 'AQtfL3oGLm', 'amoorej@blogspot.com', 39);
insert into member (username, firstName, lastName, password, email, location) values ('rgomezk', 'Roger', 'Gomez', 'Z3dakcuCj', 'rgomezk@qq.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('dperkinsl', 'Doris', 'Perkins', 'WYZGR9VuMlf', 'dperkinsl@ow.ly', 23);
insert into member (username, firstName, lastName, password, email, location) values ('cbrooksm', 'Craig', 'Brooks', 'Jxh7vmy7Iha', 'cbrooksm@google.nl', null);
insert into member (username, firstName, lastName, password, email, location) values ('khudsonn', 'Kathleen', 'Hudson', 'ZtmlMd99OBz3', 'khudsonn@nyu.edu', 7);
insert into member (username, firstName, lastName, password, email, location) values ('ehawkinso', 'Emily', 'Hawkins', '492vQurMo', 'ehawkinso@ibm.com', 89);
insert into member (username, firstName, lastName, password, email, location) values ('ahansenp', 'Andrea', 'Hansen', '7PtG7SA2B', 'ahansenp@photobucket.com', 29);
insert into member (username, firstName, lastName, password, email, location) values ('lmooreq', 'Larry', 'Moore', 'MlK7WCD6fE', 'lmooreq@epa.gov', 38);
insert into member (username, firstName, lastName, password, email, location) values ('jhansenr', 'Jeffrey', 'Hansen', '2rdgo6hhbEH', 'jhansenr@typepad.com', 77);
insert into member (username, firstName, lastName, password, email, location) values ('jwilliamsons', 'Julie', 'Williamson', 'ScV0Uc', 'jwilliamsons@histats.com', 13);
insert into member (username, firstName, lastName, password, email, location) values ('grussellt', 'Gloria', 'Russell', 'OCJpq9HE', 'grussellt@alibaba.com', 45);
insert into member (username, firstName, lastName, password, email, location) values ('spayneu', 'Scott', 'Payne', 'HCIA0Rk5ld', 'spayneu@shareasale.com', 30);
insert into member (username, firstName, lastName, password, email, location) values ('dkimv', 'Donald', 'Kim', 'IzZskNUw', 'dkimv@mtv.com', 93);
insert into member (username, firstName, lastName, password, email, location) values ('wscottw', 'Wanda', 'Scott', 'WgaWHsazZWv', 'wscottw@psu.edu', 30);
insert into member (username, firstName, lastName, password, email, location) values ('lmccoyx', 'Louis', 'Mccoy', '0nlP4so', 'lmccoyx@businessweek.com', 2);
insert into member (username, firstName, lastName, password, email, location) values ('rbradleyy', 'Rebecca', 'Bradley', 'UYe4KKu4wCG3', 'rbradleyy@slate.com', 72);
insert into member (username, firstName, lastName, password, email, location) values ('chicksz', 'Carl', 'Hicks', 'SRHmK6DQ', 'chicksz@nifty.com', 40);
insert into member (username, firstName, lastName, password, email, location) values ('pmiller10', 'Patrick', 'Miller', '5lZrFMBMSPfR', 'pmiller10@skyrock.com', 91);
insert into member (username, firstName, lastName, password, email, location) values ('smartinez11', 'Sarah', 'Martinez', 'sKHHD26wTCr', 'smartinez11@mysql.com', 43);
insert into member (username, firstName, lastName, password, email, location) values ('pharvey12', 'Patrick', 'Harvey', 'WxFTpJIK', 'pharvey12@nytimes.com', 97);
insert into member (username, firstName, lastName, password, email, location) values ('bharper13', 'Bonnie', 'Harper', 'E2ghQpPgspK9', 'bharper13@webeden.co.uk', 98);
insert into member (username, firstName, lastName, password, email, location) values ('jstephens14', 'Jose', 'Stephens', 'RyT07EO', 'jstephens14@google.co.jp', null);
insert into member (username, firstName, lastName, password, email, location) values ('mhunter15', 'Maria', 'Hunter', '5if5MYXzHJ', 'mhunter15@cbslocal.com', 65);
insert into member (username, firstName, lastName, password, email, location) values ('rcruz16', 'Russell', 'Cruz', 'BPvW2a', 'rcruz16@creativecommons.org', 8);
insert into member (username, firstName, lastName, password, email, location) values ('wrodriguez17', 'Wanda', 'Rodriguez', 'gnPiAaQb', 'wrodriguez17@nature.com', 42);
insert into member (username, firstName, lastName, password, email, location) values ('acole18', 'Albert', 'Cole', '07lUkPy7', 'acole18@amazon.de', 81);
insert into member (username, firstName, lastName, password, email, location) values ('ckelly19', 'Cheryl', 'Kelly', 'U4AeYZPweDSM', 'ckelly19@flickr.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('ereed1a', 'Eugene', 'Reed', 'IxBOkf0', 'ereed1a@loc.gov', 90);
insert into member (username, firstName, lastName, password, email, location) values ('bporter1b', 'Brandon', 'Porter', '2bgRwR9ornI', 'bporter1b@privacy.gov.au', 44);
insert into member (username, firstName, lastName, password, email, location) values ('sgomez1c', 'Shirley', 'Gomez', 'lGKeaCH', 'sgomez1c@time.com', 55);
insert into member (username, firstName, lastName, password, email, location) values ('rkennedy1d', 'Randy', 'Kennedy', '8vraxJ', 'rkennedy1d@uiuc.edu', 83);
insert into member (username, firstName, lastName, password, email, location) values ('jlong1e', 'Jeffrey', 'Long', 'aMlGGkL8F', 'jlong1e@harvard.edu', 94);
insert into member (username, firstName, lastName, password, email, location) values ('lgomez1f', 'Lillian', 'Gomez', 'lS5wL3p', 'lgomez1f@blog.com', 66);
insert into member (username, firstName, lastName, password, email, location) values ('jaustin1g', 'Jesse', 'Austin', 'ab6a51W4I', 'jaustin1g@harvard.edu', 82);
insert into member (username, firstName, lastName, password, email, location) values ('jsimmons1h', 'Joshua', 'Simmons', 'ula5iI', 'jsimmons1h@mlb.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('tcox1i', 'Tina', 'Cox', 'MLH5l5ovNvAn', 'tcox1i@chicagotribune.com', 72);
insert into member (username, firstName, lastName, password, email, location) values ('mparker1j', 'Michael', 'Parker', '6RCbvjsLXz', 'mparker1j@miitbeian.gov.cn', 80);
insert into member (username, firstName, lastName, password, email, location) values ('pwebb1k', 'Phillip', 'Webb', 'WZp4Hqi', 'pwebb1k@goo.gl', null);
insert into member (username, firstName, lastName, password, email, location) values ('sking1l', 'Sarah', 'King', 'sZGNBc3X', 'sking1l@google.co.jp', 42);
insert into member (username, firstName, lastName, password, email, location) values ('aarnold1m', 'Andrea', 'Arnold', '8SjmYUCm', 'aarnold1m@miitbeian.gov.cn', 4);
insert into member (username, firstName, lastName, password, email, location) values ('wwashington1n', 'William', 'Washington', '3wpqQTdgG', 'wwashington1n@deliciousdays.com', 33);
insert into member (username, firstName, lastName, password, email, location) values ('toliver1o', 'Tina', 'Oliver', 'aHMtqrhdKFy', 'toliver1o@shareasale.com', 26);
insert into member (username, firstName, lastName, password, email, location) values ('spierce1p', 'Samuel', 'Pierce', 'Kk5CZqPz', 'spierce1p@infoseek.co.jp', 52);
insert into member (username, firstName, lastName, password, email, location) values ('belliott1q', 'Bruce', 'Elliott', 'q0pguqcP0kV', 'belliott1q@dailymail.co.uk', 58);
insert into member (username, firstName, lastName, password, email, location) values ('mdavis1r', 'Mildred', 'Davis', '7mypJv9rm', 'mdavis1r@thetimes.co.uk', 45);
insert into member (username, firstName, lastName, password, email, location) values ('rcook1s', 'Robert', 'Cook', '1caLwH7u', 'rcook1s@addthis.com', 100);
insert into member (username, firstName, lastName, password, email, location) values ('dspencer1t', 'Donald', 'Spencer', 'WsWJEAS', 'dspencer1t@desdev.cn', 67);
insert into member (username, firstName, lastName, password, email, location) values ('mcampbell1u', 'Marilyn', 'Campbell', 'gXsjfHOo7vGT', 'mcampbell1u@comcast.net', 100);
insert into member (username, firstName, lastName, password, email, location) values ('rbryant1v', 'Raymond', 'Bryant', 'rsQbiY3F', 'rbryant1v@elpais.com', 61);
insert into member (username, firstName, lastName, password, email, location) values ('phayes1w', 'Phyllis', 'Hayes', 'YYrK1lGgpH45', 'phayes1w@businesswire.com', 24);
insert into member (username, firstName, lastName, password, email, location) values ('tsmith1x', 'Thomas', 'Smith', 'QF2UShOyXX', 'tsmith1x@dailymotion.com', 10);
insert into member (username, firstName, lastName, password, email, location) values ('bjackson1y', 'Benjamin', 'Jackson', '7rQQSK', 'bjackson1y@people.com.cn', 52);
insert into member (username, firstName, lastName, password, email, location) values ('asimmons1z', 'Anthony', 'Simmons', 'bINVU3', 'asimmons1z@hugedomains.com', 70);
insert into member (username, firstName, lastName, password, email, location) values ('kruiz20', 'Katherine', 'Ruiz', 'PY2SJGZ', 'kruiz20@thetimes.co.uk', 8);
insert into member (username, firstName, lastName, password, email, location) values ('sromero21', 'Sara', 'Romero', 'P0XfCptyJ7u', 'sromero21@netvibes.com', 47);
insert into member (username, firstName, lastName, password, email, location) values ('mthomas22', 'Mildred', 'Thomas', '4qoxoTp4o', 'mthomas22@shutterfly.com', 91);
insert into member (username, firstName, lastName, password, email, location) values ('lthompson23', 'Lawrence', 'Thompson', 'QrD9PAPA07e', 'lthompson23@cnet.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('rthompson24', 'Rachel', 'Thompson', 'qOW8v0cDb1nK', 'rthompson24@uol.com.br', 13);
insert into member (username, firstName, lastName, password, email, location) values ('jjames25', 'Jeffrey', 'James', 'j0UYD9k', 'jjames25@ask.com', 39);
insert into member (username, firstName, lastName, password, email, location) values ('dkennedy26', 'Diane', 'Kennedy', 'u7oSUmAK', 'dkennedy26@lycos.com', 47);
insert into member (username, firstName, lastName, password, email, location) values ('fmorris27', 'Fred', 'Morris', 'U960ApTnXu', 'fmorris27@usa.gov', 75);
insert into member (username, firstName, lastName, password, email, location) values ('mspencer28', 'Martha', 'Spencer', 'HjVzIwdPq', 'mspencer28@amazon.co.jp', 17);
insert into member (username, firstName, lastName, password, email, location) values ('afisher29', 'Anne', 'Fisher', 'J6AXFtzQUypX', 'afisher29@cbsnews.com', 16);
insert into member (username, firstName, lastName, password, email, location) values ('rreid2a', 'Russell', 'Reid', 'Z9lDuUxGs', 'rreid2a@myspace.com', 18);
insert into member (username, firstName, lastName, password, email, location) values ('jlittle2b', 'Jerry', 'Little', 'dvs6gMrgKYP4', 'jlittle2b@marriott.com', 78);
insert into member (username, firstName, lastName, password, email, location) values ('pmorgan2c', 'Patricia', 'Morgan', '6ko1C0KRrSzn', 'pmorgan2c@printfriendly.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('dstanley2d', 'Daniel', 'Stanley', 'qnFD1Vc7WIkk', 'dstanley2d@imgur.com', 37);
insert into member (username, firstName, lastName, password, email, location) values ('jhowell2e', 'Judith', 'Howell', 'I1FUOC', 'jhowell2e@buzzfeed.com', 66);
insert into member (username, firstName, lastName, password, email, location) values ('pfernandez2f', 'Pamela', 'Fernandez', 'DwLkQVoDuzB', 'pfernandez2f@feedburner.com', 11);
insert into member (username, firstName, lastName, password, email, location) values ('rcoleman2g', 'Rachel', 'Coleman', 'tdWUGHGv', 'rcoleman2g@dyndns.org', 62);
insert into member (username, firstName, lastName, password, email, location) values ('tknight2h', 'Teresa', 'Knight', 'FIME6iE', 'tknight2h@washington.edu', 73);
insert into member (username, firstName, lastName, password, email, location) values ('mwilson2i', 'Margaret', 'Wilson', 'Q40TJl', 'mwilson2i@ebay.co.uk', null);
insert into member (username, firstName, lastName, password, email, location) values ('sturner2j', 'Sharon', 'Turner', '5uqNFcgv', 'sturner2j@pcworld.com', 42);
insert into member (username, firstName, lastName, password, email, location) values ('rmartinez2k', 'Rose', 'Martinez', 'OlQzs82ji', 'rmartinez2k@icio.us', 17);
insert into member (username, firstName, lastName, password, email, location) values ('eross2l', 'Ernest', 'Ross', 'kEPyar0VAJ6', 'eross2l@hostgator.com', 51);
insert into member (username, firstName, lastName, password, email, location) values ('dcooper2m', 'Deborah', 'Cooper', 'u4Pqht', 'dcooper2m@aol.com', 65);
insert into member (username, firstName, lastName, password, email, location) values ('atucker2n', 'Amy', 'Tucker', 'HebWBxER', 'atucker2n@vimeo.com', 37);
insert into member (username, firstName, lastName, password, email, location) values ('slewis2o', 'Shawn', 'Lewis', 'ryI1KihbGm', 'slewis2o@bluehost.com', null);
insert into member (username, firstName, lastName, password, email, location) values ('dwheeler2p', 'Doris', 'Wheeler', 'paoqm1lG', 'dwheeler2p@google.it', 66);
insert into member (username, firstName, lastName, password, email, location) values ('jwheeler2q', 'Janice', 'Wheeler', 'Nf56sGlJMwW', 'jwheeler2q@moonfruit.com', 30);
insert into member (username, firstName, lastName, password, email, location) values ('tshaw2r', 'Todd', 'Shaw', 'quEjce5qw', 'tshaw2r@plala.or.jp', 27);

-- -----------
-- MEETINGS --
-- -----------

insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('approach', 'quam a odio in hac habitasse platea dictumst maecenas ut massa', 8, '2017-01-23', '8:31', 46, 24, 17, 48);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Graphical User Interface', 'in quis justo maecenas', 9, '2017-02-13', '23:23', 33, 64, 18, 2);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Cross-group', null, 7, '2017-05-15', '16:34', 91, 66, 21, 64);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Vision-oriented', 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 2, '2017-10-22', '18:36', 68, 14, 70, 91);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('secondary', 'morbi sem mauris laoreet', 1, '2017-03-21', '9:30', 23, 13, 14, 66);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('value-added', 'turpis nec euismod scelerisque quam turpis', 2, '2017-11-13', '21:55', 49, 32, 12, 45);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('database', 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 4, '2016-11-22', '20:39', 60, 25, 47, 13);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('impactful', 'vulputate nonummy maecenas tincidunt lacus', 8, '2017-08-22', '14:17', 79, 76, 88, 52);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Grass-roots', 'id turpis integer aliquet massa id lobortis convallis tortor risus', 2, '2017-01-30', '20:40', 26, 90, 52, 86);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('access', 'consequat metus sapien ut nunc vestibulum ante', 2, '2017-10-09', '23:40', 93, 56, 51, 20);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Re-contextualized', 'sapien arcu sed', 4, '2017-05-11', '13:33', 91, 60, 62, 100);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Programmable', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo', 9, '2017-07-30', '14:51', 21, 73, 4, 59);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Up-sized', 'vulputate', 7, '2017-04-21', '3:04', 19, 20, 90, 55);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('directional', 'suspendisse ornare consequat lectus in est risus', 7, '2017-05-07', '2:41', 7, 49, 86, 46);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Upgradable', 'imperdiet et commodo vulputate justo in blandit', 10, '2017-05-22', '2:28', 56, 53, 3, 19);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Robust', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 5, '2017-02-11', '14:46', 46, 44, 57, 30);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('data-warehouse', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis', 5, '2017-10-23', '7:14', 34, 40, 13, 7);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('modular', null, 3, '2016-11-27', '14:34', 63, 3, 14, 62);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('knowledge user', null, 7, '2017-10-07', '22:19', 66, 97, 72, 23);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('heuristic', 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 6, '2017-07-05', '1:04', 60, 54, 49, 88);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('heuristic', 'justo in blandit', 4, '2017-06-24', '13:25', 53, 65, 13, 7);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('definition', 'leo maecenas pulvinar lobortis est phasellus', 2, '2017-09-15', '16:45', 24, 69, 100, 75);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('leverage', 'diam neque vestibulum eget vulputate ut ultrices', 5, '2017-08-23', '11:01', 77, 41, 36, 1);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('composite', 'tempor turpis nec', 3, '2017-10-16', '19:42', 26, 77, 97, 97);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('middleware', 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec', 10, '2017-05-05', '15:59', 88, 67, 99, 37);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('secured line', 'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 6, '2017-05-27', '15:05', 25, 26, 11, 32);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('interactive', 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 6, '2017-06-10', '1:12', 43, 80, 13, 44);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('analyzing', 'penatibus et magnis dis parturient montes nascetur ridiculus', 8, '2016-12-20', '17:19', 42, 95, 59, 4);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('architecture', 'pharetra magna ac consequat metus sapien ut', 3, '2017-03-21', '0:48', 87, 91, 11, 40);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('moratorium', null, 10, '2017-08-14', '21:34', 19, 90, 90, 90);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Open-source', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', 7, '2017-06-17', '23:55', 20, 87, 41, 13);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Advanced', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 3, '2017-09-04', '20:13', 66, 19, 12, 15);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Multi-channelled', 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', 2, '2017-09-18', '17:28', 75, 69, 31, 95);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Devolved', 'sed nisl nunc rhoncus dui vel sem sed', 1, '2017-06-28', '2:11', 60, 55, 42, 87);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('success', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 7, '2017-03-22', '13:03', 58, 59, 21, 87);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('artificial intelligence', 'est', 9, '2017-06-10', '6:06', 71, 12, 21, 10);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Multi-layered', 'eget orci vehicula condimentum curabitur in libero', 9, '2017-06-27', '19:07', 40, 31, 1, 66);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Customizable', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 9, '2017-08-09', '13:42', 4, 71, 45, 72);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('contextually-based', 'vestibulum', 9, '2016-12-20', '20:25', 30, 32, 12, 53);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('User-friendly', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 10, '2017-03-02', '12:08', 12, 85, 1, 29);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('dynamic', 'aliquam non mauris morbi', 9, '2017-07-12', '5:22', 53, 38, 10, 30);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Diverse', 'risus semper porta volutpat quam pede lobortis ligula', 8, '2017-09-12', '13:27', 6, 27, 99, 17);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('transitional', 'nisl nunc nisl duis bibendum felis sed', 6, '2017-04-19', '19:09', 90, 5, 100, 1);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Open-source', 'eget nunc donec quis orci eget orci vehicula', 3, '2017-11-15', '8:55', 42, 26, 63, 17);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('info-mediaries', 'posuere', 2, '2017-08-17', '20:13', 67, 36, 72, 34);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('concept', 'elementum pellentesque quisque porta volutpat erat', 3, '2017-03-07', '10:20', 25, 98, 91, 81);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('stable', 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla', 10, '2017-09-04', '21:25', 36, 14, 95, 98);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('tertiary', null, 4, '2017-07-02', '5:28', 5, 67, 58, 90);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('4th generation', 'lacinia nisi venenatis tristique fusce congue', 10, '2017-03-17', '11:09', 50, 54, 13, 90);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('challenge', 'nam nulla', 1, '2017-10-01', '13:54', 87, 94, 54, 8);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('help-desk', 'lectus in est risus', 8, '2017-07-14', '18:14', 14, 8, 18, 80);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Triple-buffered', 'condimentum neque sapien', 8, '2017-10-05', '11:40', 80, 16, 66, 30);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('contextually-based', null, 1, '2016-11-29', '18:05', 10, 82, 12, 60);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('systematic', 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla', 3, '2017-03-13', '7:26', 69, 85, 75, 4);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Synchronised', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 6, '2017-01-07', '9:13', 92, 53, 1, 93);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Ameliorated', 'ut massa volutpat convallis morbi odio odio elementum', 8, '2017-02-04', '22:48', 81, 82, 81, 85);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Secured', 'quisque id justo sit amet sapien dignissim', 8, '2017-09-21', '21:11', 68, 5, 52, 26);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Stand-alone', 'tristique est et', 10, '2017-07-18', '18:24', 36, 62, 54, 89);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('frame', null, 10, '2016-12-12', '18:12', 100, 51, 86, 21);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('coherent', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 10, '2017-10-24', '5:24', 71, 48, 23, 61);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Automated', 'in consequat ut nulla sed accumsan', 4, '2017-04-21', '0:19', 23, 7, 57, 48);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('analyzing', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 9, '2017-04-08', '4:42', 4, 19, 18, 47);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('content-based', 'justo nec condimentum neque sapien placerat ante nulla', 5, '2017-11-15', '6:35', 65, 48, 53, 62);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('interactive', 'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate', 4, '2017-09-15', '5:16', 41, 7, 56, 4);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('hardware', 'justo', 9, '2017-07-21', '4:09', 95, 71, 67, 46);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('dedicated', 'at velit eu', 3, '2017-04-05', '0:09', 93, 96, 81, 97);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('methodology', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', 8, '2017-04-27', '6:16', 19, 87, 8, 20);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('human-resource', 'quis odio consequat varius integer ac leo pellentesque', 10, '2017-05-16', '13:16', 49, 40, 61, 62);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Multi-layered', 'et tempus semper est quam pharetra magna ac consequat', 7, '2017-04-24', '9:43', 54, 89, 55, 6);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('instruction set', 'amet nulla quisque arcu libero rutrum ac', 6, '2017-09-26', '21:04', 54, 75, 32, 95);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('discrete', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', 9, '2016-12-22', '23:50', 68, 14, 49, 89);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('full-range', 'nunc viverra dapibus nulla suscipit ligula in', 8, '2017-04-20', '12:14', 2, 9, 43, 37);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('User-friendly', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 2, '2017-03-17', '7:36', 4, 2, 73, 2);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('bottom-line', 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', 5, '2017-11-05', '2:02', 28, 67, 55, 16);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Digitized', 'hac habitasse platea dictumst etiam faucibus cursus urna ut tellus', 4, '2017-03-10', '6:12', 11, 53, 42, 31);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Secured', 'erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 6, '2017-07-18', '22:46', 35, 61, 88, 76);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('motivating', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 9, '2017-08-30', '5:58', 34, 97, 42, 95);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('empowering', 'magna bibendum imperdiet', 9, '2016-12-20', '15:11', 68, 25, 47, 68);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('archive', null, 1, '2017-05-02', '8:22', 57, 43, 36, 58);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Enterprise-wide', 'varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', 6, '2016-12-08', '6:34', 89, 39, 52, 29);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Horizontal', 'amet sem fusce consequat', 2, '2017-09-05', '6:11', 22, 30, 75, 15);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Re-engineered', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 5, '2017-07-08', '3:12', 71, 17, 9, 41);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('incremental', 'purus', 6, '2017-07-30', '20:42', 16, 95, 40, 35);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('ability', 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 9, '2017-03-15', '12:12', 36, 38, 27, 9);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Organized', 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', 5, '2017-01-31', '4:24', 6, 77, 77, 78);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('definition', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 6, '2017-08-03', '10:34', 79, 46, 26, 57);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('attitude-oriented', 'phasellus sit amet erat nulla tempus vivamus in felis eu', 7, '2017-07-29', '16:51', 25, 42, 36, 35);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('implementation', 'neque vestibulum', 7, '2017-05-07', '2:57', 68, 33, 82, 79);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('optimizing', null, 8, '2017-05-31', '21:42', 35, 50, 26, 11);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Vision-oriented', 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', 6, '2016-11-30', '17:36', 57, 21, 92, 20);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('interface', 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum', 3, '2017-02-19', '16:14', 62, 88, 80, 35);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('next generation', 'magna at nunc', 9, '2017-01-25', '9:04', 73, 43, 80, 13);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('5th generation', 'quis justo maecenas rhoncus aliquam lacus morbi', 1, '2017-06-22', '19:11', 13, 30, 73, 89);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('help-desk', null, 1, '2017-10-30', '23:53', 43, 39, 69, 69);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('protocol', 'rutrum rutrum neque aenean auctor gravida sem praesent id', 4, '2017-03-16', '13:50', 49, 25, 19, 87);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('leverage', 'urna pretium nisl ut', 8, '2017-09-27', '16:10', 15, 34, 31, 41);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('matrices', 'nascetur ridiculus mus etiam vel augue vestibulum rutrum', 5, '2017-06-25', '16:03', 32, 61, 19, 96);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('Reactive', 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 8, '2017-01-24', '0:14', 51, 99, 57, 53);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('open architecture', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 2, '2017-04-01', '23:39', 31, 51, 10, 45);
insert into meeting (name, description, category, meetingDate, meetingTime, meetingLocation, meetingOwner, maxMembers, createdLocation) values ('utilisation', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 3, '2017-08-06', '13:55', 84, 83, 29, 2);

-- --------
-- MEETS --
-- --------

INSERT INTO meet (member, meeting) VALUES (31, 85);
INSERT INTO meet (member, meeting) VALUES (17, 88);
INSERT INTO meet (member, meeting) VALUES (44, 18);
INSERT INTO meet (member, meeting) VALUES (44, 62);
INSERT INTO meet (member, meeting) VALUES (44, 7);
INSERT INTO meet (member, meeting) VALUES (37, 40);
INSERT INTO meet (member, meeting) VALUES (25, 58);
INSERT INTO meet (member, meeting) VALUES (25, 70);
INSERT INTO meet (member, meeting) VALUES (14, 75);
INSERT INTO meet (member, meeting) VALUES (16, 17);
INSERT INTO meet (member, meeting) VALUES (18, 38);
INSERT INTO meet (member, meeting) VALUES (44, 84);
INSERT INTO meet (member, meeting) VALUES (45, 83);
INSERT INTO meet (member, meeting) VALUES (10, 67);
INSERT INTO meet (member, meeting) VALUES (5, 51);
INSERT INTO meet (member, meeting) VALUES (34, 52);
INSERT INTO meet (member, meeting) VALUES (16, 42);
INSERT INTO meet (member, meeting) VALUES (23, 78);
INSERT INTO meet (member, meeting) VALUES (38, 16);
INSERT INTO meet (member, meeting) VALUES (42, 39);
INSERT INTO meet (member, meeting) VALUES (26, 7);
INSERT INTO meet (member, meeting) VALUES (10, 21);
INSERT INTO meet (member, meeting) VALUES (44, 9);
INSERT INTO meet (member, meeting) VALUES (45, 93);
INSERT INTO meet (member, meeting) VALUES (2, 67);
INSERT INTO meet (member, meeting) VALUES (13, 86);
INSERT INTO meet (member, meeting) VALUES (17, 34);
INSERT INTO meet (member, meeting) VALUES (46, 26);
INSERT INTO meet (member, meeting) VALUES (9, 26);
INSERT INTO meet (member, meeting) VALUES (24, 95);
INSERT INTO meet (member, meeting) VALUES (38, 48);
INSERT INTO meet (member, meeting) VALUES (33, 77);
INSERT INTO meet (member, meeting) VALUES (50, 5);
INSERT INTO meet (member, meeting) VALUES (40, 100);
INSERT INTO meet (member, meeting) VALUES (34, 13);
INSERT INTO meet (member, meeting) VALUES (32, 24);
INSERT INTO meet (member, meeting) VALUES (44, 6);
INSERT INTO meet (member, meeting) VALUES (42, 40);
INSERT INTO meet (member, meeting) VALUES (43, 86);
INSERT INTO meet (member, meeting) VALUES (37, 59);
INSERT INTO meet (member, meeting) VALUES (36, 8);
INSERT INTO meet (member, meeting) VALUES (7, 51);
INSERT INTO meet (member, meeting) VALUES (39, 11);
INSERT INTO meet (member, meeting) VALUES (45, 61);
INSERT INTO meet (member, meeting) VALUES (15, 34);
INSERT INTO meet (member, meeting) VALUES (28, 91);
INSERT INTO meet (member, meeting) VALUES (33, 5);
INSERT INTO meet (member, meeting) VALUES (49, 70);
INSERT INTO meet (member, meeting) VALUES (4, 42);
INSERT INTO meet (member, meeting) VALUES (13, 66);
INSERT INTO meet (member, meeting) VALUES (18, 80);
INSERT INTO meet (member, meeting) VALUES (23, 69);
INSERT INTO meet (member, meeting) VALUES (45, 48);
INSERT INTO meet (member, meeting) VALUES (38, 22);
INSERT INTO meet (member, meeting) VALUES (18, 71);
INSERT INTO meet (member, meeting) VALUES (20, 5);
INSERT INTO meet (member, meeting) VALUES (26, 79);
INSERT INTO meet (member, meeting) VALUES (41, 44);
INSERT INTO meet (member, meeting) VALUES (47, 96);
INSERT INTO meet (member, meeting) VALUES (15, 43);
INSERT INTO meet (member, meeting) VALUES (32, 38);
INSERT INTO meet (member, meeting) VALUES (4, 80);
INSERT INTO meet (member, meeting) VALUES (35, 64);
INSERT INTO meet (member, meeting) VALUES (5, 19);
INSERT INTO meet (member, meeting) VALUES (36, 49);
INSERT INTO meet (member, meeting) VALUES (15, 78);
INSERT INTO meet (member, meeting) VALUES (8, 68);
INSERT INTO meet (member, meeting) VALUES (35, 90);
INSERT INTO meet (member, meeting) VALUES (23, 91);
INSERT INTO meet (member, meeting) VALUES (25, 13);

