-- ----------
-- DOMAINS --
-- ----------
INSERT INTO emaildomain (domainName) VALUES ('addtoany.com');
INSERT INTO emaildomain (domainName) VALUES ('4shared.com');
INSERT INTO emaildomain (domainName) VALUES ('angelfire.com');
INSERT INTO emaildomain (domainName) VALUES ('youku.com');
INSERT INTO emaildomain (domainName) VALUES ('ustream.tv');
INSERT INTO emaildomain (domainName) VALUES ('pagesperso-orange.fr');
INSERT INTO emaildomain (domainName) VALUES ('facebook.com');
INSERT INTO emaildomain (domainName) VALUES ('mozilla.org');
INSERT INTO emaildomain (domainName) VALUES ('free.fr');
INSERT INTO emaildomain (domainName) VALUES ('microsoft.com');
INSERT INTO emaildomain (domainName) VALUES ('tamu.edu');
INSERT INTO emaildomain (domainName) VALUES ('yahoo.com');
INSERT INTO emaildomain (domainName) VALUES ('biblegateway.com');
INSERT INTO emaildomain (domainName) VALUES ('mit.edu');
INSERT INTO emaildomain (domainName) VALUES ('weibo.com');
INSERT INTO emaildomain (domainName) VALUES ('oracle.com');
INSERT INTO emaildomain (domainName) VALUES ('gnu.org');
INSERT INTO emaildomain (domainName) VALUES ('mediafire.com');
INSERT INTO emaildomain (domainName) VALUES ('discuz.net');
INSERT INTO emaildomain (domainName) VALUES ('businesswire.com');
INSERT INTO emaildomain (domainName) VALUES ('springer.com');
INSERT INTO emaildomain (domainName) VALUES ('javac.com');
INSERT INTO emaildomain (domainName) VALUES ('msu.edu');
INSERT INTO emaildomain (domainName) VALUES ('web.de');
INSERT INTO emaildomain (domainName) VALUES ('meets.de');
INSERT INTO emaildomain (domainName) VALUES ('yellowbook.com');
INSERT INTO emaildomain (domainName) VALUES ('privacy.gov.au');
INSERT INTO emaildomain (domainName) VALUES ('ow.ly');
INSERT INTO emaildomain (domainName) VALUES ('forbes.com');
INSERT INTO emaildomain (domainName) VALUES ('army.mil');
INSERT INTO emaildomain (domainName) VALUES ('ihg.com');
INSERT INTO emaildomain (domainName) VALUES ('ebay.co.uk');
INSERT INTO emaildomain (domainName) VALUES ('hostgator.com');
INSERT INTO emaildomain (domainName) VALUES ('csmonitor.com');
INSERT INTO emaildomain (domainName) VALUES ('msn.com');
INSERT INTO emaildomain (domainName) VALUES ('rediff.com');
INSERT INTO emaildomain (domainName) VALUES ('nsw.gov.au');
INSERT INTO emaildomain (domainName) VALUES ('narod.ru');
INSERT INTO emaildomain (domainName) VALUES ('ucoz.ru');
INSERT INTO emaildomain (domainName) VALUES ('com.com');
INSERT INTO emaildomain (domainName) VALUES ('indiatimes.com');
INSERT INTO emaildomain (domainName) VALUES ('elpais.com');
INSERT INTO emaildomain (domainName) VALUES ('skype.com');
INSERT INTO emaildomain (domainName) VALUES ('sciencedirect.com');
INSERT INTO emaildomain (domainName) VALUES ('comcast.net');
INSERT INTO emaildomain (domainName) VALUES ('t.co');
INSERT INTO emaildomain (domainName) VALUES ('globo.com');
INSERT INTO emaildomain (domainName) VALUES ('zimbio.com');
INSERT INTO emaildomain (domainName) VALUES ('wired.com');
INSERT INTO emaildomain (domainName) VALUES ('drop.com');

-- -------------
-- CATEGORIES --
-- -------------
INSERT INTO category (categoryName) VALUES ('Cardguard');
INSERT INTO category (categoryName) VALUES ('Viva');
INSERT INTO category (categoryName) VALUES ('Span');
INSERT INTO category (categoryName) VALUES ('Wrapsafe');
INSERT INTO category (categoryName) VALUES ('Sonair');
INSERT INTO category (categoryName) VALUES ('Bytecard');
INSERT INTO category (categoryName) VALUES ('Subin');
INSERT INTO category (categoryName) VALUES ('Regrant');
INSERT INTO category (categoryName) VALUES ('Flexidy');
INSERT INTO category (categoryName) VALUES ('Prodder');

-- ------------
-- LOCATIONS --
-- ------------

INSERT INTO location (postalCode, locName) VALUES (82887, 'Badin');
INSERT INTO location (postalCode, locName) VALUES (28254, 'Cau Giay');
INSERT INTO location (postalCode, locName) VALUES (18105, 'Batelov');
INSERT INTO location (postalCode, locName) VALUES (24186, 'Tallbisah');
INSERT INTO location (postalCode, locName) VALUES (29781, 'Buenavista');
INSERT INTO location (postalCode, locName) VALUES (71637, 'Laylay');
INSERT INTO location (postalCode, locName) VALUES (95468, 'Gorki');
INSERT INTO location (postalCode, locName) VALUES (65344, 'Jiachuan');
INSERT INTO location (postalCode, locName) VALUES (61535, 'Ngurensiti');
INSERT INTO location (postalCode, locName) VALUES (78546, 'Tertek');
INSERT INTO location (postalCode, locName) VALUES (88852, 'Sirnasari');
INSERT INTO location (postalCode, locName) VALUES (54326, 'Tungelsta');
INSERT INTO location (postalCode, locName) VALUES (25855, 'San Jose de las Lajas');
INSERT INTO location (postalCode, locName) VALUES (95589, 'Kuripan');
INSERT INTO location (postalCode, locName) VALUES (30569, 'Hekou');
INSERT INTO location (postalCode, locName) VALUES (17350, 'Yuli');
INSERT INTO location (postalCode, locName) VALUES (62378, 'Norberg');
INSERT INTO location (postalCode, locName) VALUES (72819, 'Nizhniye Vyazovyye');
INSERT INTO location (postalCode, locName) VALUES (44360, 'Abiko');
INSERT INTO location (postalCode, locName) VALUES (57913, 'Lamawan');
INSERT INTO location (postalCode, locName) VALUES (73641, 'Norrköping');
INSERT INTO location (postalCode, locName) VALUES (92858, 'Sanxiang');
INSERT INTO location (postalCode, locName) VALUES (68914, 'Jedlnia-Letnisko');
INSERT INTO location (postalCode, locName) VALUES (93680, 'Aix-en-Provence');
INSERT INTO location (postalCode, locName) VALUES (41801, 'Ramenki');
INSERT INTO location (postalCode, locName) VALUES (89114, 'Rivera');
INSERT INTO location (postalCode, locName) VALUES (43255, 'Futian');
INSERT INTO location (postalCode, locName) VALUES (60502, 'Renfengzhuang');
INSERT INTO location (postalCode, locName) VALUES (28373, 'Qiying');
INSERT INTO location (postalCode, locName) VALUES (73213, 'Fushe-Bulqize');
INSERT INTO location (postalCode, locName) VALUES (78669, 'Rantau');
INSERT INTO location (postalCode, locName) VALUES (79580, 'Al Humaydat');
INSERT INTO location (postalCode, locName) VALUES (11044, 'San Francisco');
INSERT INTO location (postalCode, locName) VALUES (46332, 'Pamiers');
INSERT INTO location (postalCode, locName) VALUES (25425, 'Guanghai');
INSERT INTO location (postalCode, locName) VALUES (80278, 'Örebro');
INSERT INTO location (postalCode, locName) VALUES (53333, 'Paris 14');
INSERT INTO location (postalCode, locName) VALUES (41538, 'Facatativa');
INSERT INTO location (postalCode, locName) VALUES (71298, 'Grabow nad Prosna');
INSERT INTO location (postalCode, locName) VALUES (79541, 'Storvik');
INSERT INTO location (postalCode, locName) VALUES (52527, 'Governador Valadares');
INSERT INTO location (postalCode, locName) VALUES (69361, 'Sagae');
INSERT INTO location (postalCode, locName) VALUES (20614, 'Jiuhua');
INSERT INTO location (postalCode, locName) VALUES (24087, 'Bogo');
INSERT INTO location (postalCode, locName) VALUES (57954, 'Shache');
INSERT INTO location (postalCode, locName) VALUES (79112, 'Hellevoetsluis');
INSERT INTO location (postalCode, locName) VALUES (37843, 'Zhulebino');
INSERT INTO location (postalCode, locName) VALUES (21835, 'Gnosjö');
INSERT INTO location (postalCode, locName) VALUES (70162, 'Lam Thao');
INSERT INTO location (postalCode, locName) VALUES (33186, 'Cheongsong gun');
INSERT INTO location (postalCode, locName) VALUES (85457, 'Cikandang');
INSERT INTO location (postalCode, locName) VALUES (77075, 'Doug An');
INSERT INTO location (postalCode, locName) VALUES (81985, 'Timezgadiouine');
INSERT INTO location (postalCode, locName) VALUES (94946, 'Dayton');
INSERT INTO location (postalCode, locName) VALUES (93051, 'Ban Lam Luk Ka');
INSERT INTO location (postalCode, locName) VALUES (79149, 'Banjar Dharmasemedi');
INSERT INTO location (postalCode, locName) VALUES (82751, 'Maloarkhangelsk');
INSERT INTO location (postalCode, locName) VALUES (95215, 'Vyatskiye Polyany');
INSERT INTO location (postalCode, locName) VALUES (93274, 'Lexington');
INSERT INTO location (postalCode, locName) VALUES (18336, 'Nürnberg');
INSERT INTO location (postalCode, locName) VALUES (26370, 'Mayong');
INSERT INTO location (postalCode, locName) VALUES (54251, 'Lewograran');
INSERT INTO location (postalCode, locName) VALUES (69753, 'Ipora');
INSERT INTO location (postalCode, locName) VALUES (11121, 'Nar-yan-Mar');
INSERT INTO location (postalCode, locName) VALUES (86001, 'Getazat');
INSERT INTO location (postalCode, locName) VALUES (41438, 'Nicolas Bravo');
INSERT INTO location (postalCode, locName) VALUES (66403, 'Hejiabao');
INSERT INTO location (postalCode, locName) VALUES (63850, 'Lusaka');
INSERT INTO location (postalCode, locName) VALUES (33309, 'Tamboril');
INSERT INTO location (postalCode, locName) VALUES (64447, 'Si Mahosot');
INSERT INTO location (postalCode, locName) VALUES (57330, 'Qiling');
INSERT INTO location (postalCode, locName) VALUES (25771, 'Lobanovo');
INSERT INTO location (postalCode, locName) VALUES (98213, 'Brumado');
INSERT INTO location (postalCode, locName) VALUES (92419, 'Krajanbonjor');
INSERT INTO location (postalCode, locName) VALUES (33586, 'Gorzow Slaski');
INSERT INTO location (postalCode, locName) VALUES (87157, 'Leuweheq');
INSERT INTO location (postalCode, locName) VALUES (86611, 'Kampungruweh');
INSERT INTO location (postalCode, locName) VALUES (65080, 'Tsotsin-Yurt');
INSERT INTO location (postalCode, locName) VALUES (69697, 'Heichengzi');
INSERT INTO location (postalCode, locName) VALUES (76613, 'Jiulong');
INSERT INTO location (postalCode, locName) VALUES (85536, 'Campos Belos');
INSERT INTO location (postalCode, locName) VALUES (11646, 'Iecava');
INSERT INTO location (postalCode, locName) VALUES (60261, 'Ostrov');
INSERT INTO location (postalCode, locName) VALUES (81727, 'Bom Jesus do Itabapoana');
INSERT INTO location (postalCode, locName) VALUES (13882, 'Long’an Chengxiangzhen');
INSERT INTO location (postalCode, locName) VALUES (22398, 'Uubulan');
INSERT INTO location (postalCode, locName) VALUES (79235, 'Ismayilli');
INSERT INTO location (postalCode, locName) VALUES (68001, 'Poniatowa');
INSERT INTO location (postalCode, locName) VALUES (72192, 'Xiuyu');
INSERT INTO location (postalCode, locName) VALUES (52147, 'Västeras');
INSERT INTO location (postalCode, locName) VALUES (42770, 'Muhambal');
INSERT INTO location (postalCode, locName) VALUES (42355, 'Esigodini');
INSERT INTO location (postalCode, locName) VALUES (44408, 'Jiaokou');
INSERT INTO location (postalCode, locName) VALUES (89998, 'San Jose');
INSERT INTO location (postalCode, locName) VALUES (16621, 'Qingyang');
INSERT INTO location (postalCode, locName) VALUES (78884, 'Cabucgayan');
INSERT INTO location (postalCode, locName) VALUES (62969, 'Amnat Charoen');
INSERT INTO location (postalCode, locName) VALUES (20569, 'Hluboka nad Vltavou');
INSERT INTO location (postalCode, locName) VALUES (12672, 'San Pedro Apartado');
INSERT INTO location (postalCode, locName) VALUES (72184, 'Yuannan');

-- ----------
-- MEMBERS --
-- ----------

INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('ereynolds0', 'Earl', 'Reynolds', 'uEjsbJ', 'It', 35);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('mjackson1', 'Martha', 'Jackson', '5VrbKTMSo', 'Sonsing', 30);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('lgray2', 'Linda', 'Gray', '6j5hbPcSt4qo', 'Zathin', 10);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jbell3', 'Joan', 'Bell', 'dkYITC7', 'Duobam', 15);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('iharrison4', 'Irene', 'Harrison', 'EqMGPEwp4', 'Flexidy', 45);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('candrews5', 'Carolyn', 'Andrews', 'mCyuUmTTL8d', 'Tresom', 1);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('mmoore6', 'Mary', 'Moore', 'z7oUB5oLp1', 'Zaam-Dox', 49);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('aburton7', 'Annie', 'Burton', 'LLfp1Jx6O6Ga', 'Namfix', 23);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('bjohnson8', 'Brian', 'Johnson', 'c3x7RtQqp', 'Zoolab', 38);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('lcole9', 'Laura', 'Cole', '4blW8zwgPr', 'Solarbreeze', 33);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rnicholsa', 'Robin', 'Nichols', 'aepuUPKim4N2', 'Vagram', 28);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('khawkinsb', 'Keith', 'Hawkins', 'bycdtH3S', 'Pannier', 23);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jbryantc', 'Jennifer', 'Bryant', 'lzvzR6pT', 'Sub-Ex', 25);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('acampbelld', 'Arthur', 'Campbell', 'IwSrG3', 'Biodex', 27);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('cpalmere', 'Carl', 'Palmer', 'BKn3Tw9N3', 'Namfix', 46);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('pbutlerf', 'Paul', 'Butler', 'BWkeHjM', 'Regrant', 46);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('drichardsong', 'Donald', 'Richardson', 'au3Ayj', 'Konklux', 37);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('adeanh', 'Amy', 'Dean', 'SY1WWXT', 'Subin', 36);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('sruizi', 'Sarah', 'Ruiz', 'gECmSaCufp', 'Tres-Zap', 45);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('emyersj', 'Edward', 'Myers', 't8z11aeRO9s', 'Y-find', 25);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jmasonk', 'Jimmy', 'Mason', 'I1eAJi', 'Tampflex', 3);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('bcookl', 'Brandon', 'Cook', '7AvRzqzAECRl', 'Stringtough', 37);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('alynchm', 'Andrew', 'Lynch', 'LdsPhMdt5eb', 'Y-Solowarm', 22);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('kfoxn', 'Kevin', 'Fox', '0IvLzEn', 'Rank', 39);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('dalexandero', 'Daniel', 'Alexander', 'U2VA4mCRiwl', 'Greenlam', 12);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rstevensp', 'Ruth', 'Stevens', 'eSs5LeV7arLn', 'Y-find', 45);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jwillisq', 'Joseph', 'Willis', 'oeeyNs', 'Tempsoft', 20);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('scarrr', 'Scott', 'Carr', 'l6gLMVfM', 'Toughjoyfax', 5);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('ewarrens', 'Eugene', 'Warren', 'xETTzIYX', 'Voltsillam', 44);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('kbradleyt', 'Kathryn', 'Bradley', 'suL51k', 'Alpha', 37);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('mporteru', 'Margaret', 'Porter', 'u2pSb2ZHf', 'Sub-Ex', 44);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('ejamesv', 'Earl', 'James', '0Ie7T5EaX', 'Cardguard', 27);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('shawkinsw', 'Sharon', 'Hawkins', '9BlR9QkHNBVo', 'Sonsing', 26);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('efranklinx', 'Ernest', 'Franklin', '2vm109wroTy', 'Greenlam', 14);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('scarpentery', 'Steven', 'Carpenter', 'PvXvClKE88W', 'Tampflex', 17);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rcruzz', 'Ralph', 'Cruz', 'rUKQNhq6mFsg', 'Tin', 20);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('smatthews10', 'Sharon', 'Matthews', 'cwtSqyUsv6vR', 'Flexidy', 26);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('fdaniels11', 'Frank', 'Daniels', '4YRXMXZNc', 'Quo Lux', 42);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('dharper12', 'Diane', 'Harper', 'hImQkdv0', 'Alphazap', 42);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('bmarshall13', 'Billy', 'Marshall', 'AP0DNfUntVWR', 'Subin', 48);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('grichardson14', 'Gloria', 'Richardson', 'HGzPbZ', 'Tres-Zap', 23);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rbradley15', 'Roy', 'Bradley', 'CnaNIIy', 'Asoka', 46);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('whicks16', 'Wanda', 'Hicks', 'lERgDGIVNm', 'Sub-Ex', 18);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('gmoore17', 'Gregory', 'Moore', 'bDOEeIHTfrA', 'Voltsillam', 25);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('djohnson18', 'Doris', 'Johnson', 'q5oSAUcwIUpF', 'Lotstring', 28);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jhowell19', 'Juan', 'Howell', 'GpMUuNI', 'Zoolab', 19);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rhawkins1a', 'Randy', 'Hawkins', '3rP0NKicU', 'Lotlux', 46);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('psanders1b', 'Patricia', 'Sanders', '9MtLNlaQC', 'Subin', 32);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jstephens1c', 'Judith', 'Stephens', 'MjUU1PWiq', 'Overhold', 12);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('gbanks1d', 'Gloria', 'Banks', '3Zu0XU7QnWom', 'Stronghold', 29);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('gjohnston1e', 'George', 'Johnston', 'hS9lkl', 'Veribet', 34);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('lrivera1f', 'Lisa', 'Rivera', 'YS2NIh1a', 'Biodex', 26);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rsullivan1g', 'Robert', 'Sullivan', 'ubRbht8UE6', 'Cookley', 36);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('pbanks1h', 'Paul', 'Banks', 'C6DZwoNW', 'Span', 14);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('dwright1i', 'Daniel', 'Wright', 'gh58hoe7', 'Sub-Ex', 30);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('drivera1j', 'Douglas', 'Rivera', 'MXh9gtS5i', 'Stim', 16);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('ryoung1k', 'Robin', 'Young', 'G5kj6XklY', 'Alphazap', 50);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('awilson1l', 'Ashley', 'Wilson', 'cUQsBoV', 'Ronstring', 44);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('bhill1m', 'Bruce', 'Hill', 'vCf4BJ1n', 'Ronstring', 11);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('lwhite1n', 'Larry', 'White', 'uM3apK94sv', 'Aerified', 3);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jhill1o', 'Jeffrey', 'Hill', 'mO08JHgPNMW', 'Viva', 48);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rreid1p', 'Russell', 'Reid', '4d7K1sKRos', 'Duobam', 14);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jwillis1q', 'Jason', 'Willis', 'x6sf0G', 'Transcof', 36);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('hhart1r', 'Harry', 'Hart', 'g2rgWUh5RF', 'Opela', 18);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('aday1s', 'Amanda', 'Day', '18ASHp7N1', 'Zoolab', 19);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('mmorgan1t', 'Margaret', 'Morgan', 'OwYnflHY', 'Bamity', 39);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jelliott1u', 'Johnny', 'Elliott', 'Vy3B4D9zXaa', 'Tempsoft', 33);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('gpalmer1v', 'Gregory', 'Palmer', '4e4bYVDK4', 'Duobam', 14);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jpatterson1w', 'Jerry', 'Patterson', 'lg6RLkL', 'Lotlux', 23);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('dhowell1x', 'Dorothy', 'Howell', 'Rr5fal1im', 'Duobam', 29);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('mrose1y', 'Martha', 'Rose', 'FDcYJclRmfb', 'Tresom', 45);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('dwilliams1z', 'Daniel', 'Williams', 'lhjK5hZ', 'Andalax', 39);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rgarcia20', 'Rebecca', 'Garcia', 'TL6McRA1', 'Tresom', 45);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('pstewart21', 'Peter', 'Stewart', 'zABQA7ySRtxO', 'Flexidy', 16);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('kcook22', 'Katherine', 'Cook', 'paTkGaeE', 'Tresom', 40);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('sschmidt23', 'Stephen', 'Schmidt', 'toMu03Bez', 'Pannier', 2);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('halexander24', 'Howard', 'Alexander', 'k9lfA751WbbZ', 'Zaam-Dox', 6);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('msims25', 'Melissa', 'Sims', 'kD8FDLBNk', 'Lotstring', 47);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('tgomez26', 'Timothy', 'Gomez', 'pJsLb1J', 'Y-Solowarm', 5);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jmccoy27', 'Joseph', 'Mccoy', 'jOUgjXZ1UpS', 'Konklux', 46);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('agreen28', 'Amy', 'Green', 'tCde7nczj', 'Opela', 5);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('tburton29', 'Tammy', 'Burton', 'a6VnqSTI', 'Fixflex', 4);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('asullivan2a', 'Anne', 'Sullivan', 'Ngqkh5dO', 'Fixflex', 22);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('bbennett2b', 'Bruce', 'Bennett', 'S3ICSnMbEYdR', 'It', 30);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jmyers2c', 'Jason', 'Myers', 'dR9a1vr4A0G', 'Namfix', 7);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('adixon2d', 'Aaron', 'Dixon', 'ReO7mh', 'Overhold', 44);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('brivera2e', 'Beverly', 'Rivera', 'Myu5jqDoqbc', 'Stronghold', 31);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('belliott2f', 'Bonnie', 'Elliott', '9PrwTyjN', 'Bytecard', 21);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jcampbell2g', 'Jack', 'Campbell', 'kHMdig1', 'Overhold', 39);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('ahall2h', 'Albert', 'Hall', 'BglWSEiBwpB', 'Biodex', 39);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('gmorgan2i', 'Gloria', 'Morgan', 'kK6iMFz', 'Subin', 18);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jwatkins2j', 'John', 'Watkins', 'RuT0f9T80c8', 'Asoka', 35);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('sjohnson2k', 'Shirley', 'Johnson', '0GMaYuylK', 'Cardify', 30);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('rwillis2l', 'Robin', 'Willis', 'R3DOQ9Wb5b', 'Tres-Zap', 2);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('sbrooks2m', 'Sandra', 'Brooks', 'SWV6zaFyLTUC', 'Asoka', 24);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jhicks2n', 'Julia', 'Hicks', '2gOMYRmq', 'Viva', 38);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('dalvarez2o', 'Diana', 'Alvarez', 'dqZHR5DT', 'Holdlamis', 17);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jalexander2p', 'Jonathan', 'Alexander', 'ayNiSMNuw9t', 'Tres-Zap', 19);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('jthomas2q', 'Jeremy', 'Thomas', 'suBBnlusEzU', 'Stringtough', 48);
INSERT INTO member (username, preName, surName, memberPW, mailContact, mailDomain) VALUES ('tbanks2r', 'Thomas', 'Banks', 'JMCR6BiRg', 'Veribet', 45);

-- -----------
-- MEETINGS --
-- -----------

INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Transcof', 'etiam justo etiam pretium iaculis justo in hac habitasse platea', 9, 6, '2017-07-04 18:25:24', '2016-12-20 01:45:23', 26, 4, 36);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Bamity', 'cras mi pede malesuada in', 7, 8, '2017-07-18 20:24:27', '2017-09-08 03:01:11', 57, 57, 31);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Kanlam', 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 4, 3, '2017-11-02 01:05:58', '2017-01-10 20:16:42', 58, 76, 38);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Y-Solowarm', 'nunc nisl duis bibendum felis sed interdum venenatis', 3, 15, '2017-01-07 19:22:09', '2017-07-24 08:23:51', 70, 62, 26);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Sonsing', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', 6, 2, '2017-06-10 21:20:40', '2017-01-01 15:58:21', 43, 95, 2);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zaam-Dox', 'iaculis', 2, 15, '2017-03-21 10:28:56', '2017-11-07 01:46:50', 67, 5, 35);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Trippledex', 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 1, 2, '2017-03-08 23:32:36', '2017-01-21 21:37:07', 92, 41, 49);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Holdlamis', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', 5, 5, '2017-09-03 23:35:15', '2016-12-12 18:15:43', 41, 91, 28);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Greenlam', 'nulla elit ac nulla sed vel enim sit amet', 6, 6, '2017-05-05 09:30:03', '2017-06-14 11:31:42', 5, 28, 39);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Ronstring', 'massa tempor convallis nulla neque libero', 5, 5, '2017-09-16 05:00:21', '2017-01-16 23:22:29', 99, 51, 25);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Daltfresh', 'massa donec dapibus duis at velit', 5, 12, '2016-12-07 06:04:04', '2017-07-01 09:21:20', 14, 85, 29);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Sub-Ex', 'eget eleifend luctus ultricies eu nibh', 5, 4, '2016-12-19 15:22:12', '2017-10-04 18:28:05', 10, 96, 34);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Pannier', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', 9, 14, '2017-02-02 04:18:37', '2016-12-13 18:43:31', 59, 52, 12);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Latlux', 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 10, 12, '2017-01-17 03:39:56', '2017-08-10 13:49:36', 16, 98, 22);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('It', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna', 10, 4, '2017-07-01 16:41:06', '2017-08-22 14:22:07', 94, 82, 1);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Bigtax', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', 3, 3, '2017-03-24 18:17:01', '2017-11-12 18:11:50', 17, 55, 31);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Flexidy', 'elit ac nulla sed vel enim sit amet nunc', 2, 13, '2017-02-12 17:23:59', '2017-06-10 12:28:56', 39, 86, 46);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zaam-Dox', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 5, 7, '2017-03-08 18:56:07', '2017-05-11 05:51:22', 75, 54, 41);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Stronghold', 'morbi non quam nec dui luctus rutrum', 7, 4, '2016-11-26 22:07:04', '2017-09-12 19:13:07', 80, 81, 26);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Keylex', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 9, 6, '2017-02-22 14:28:34', '2017-02-26 06:59:58', 62, 59, 39);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Treeflex', 'suscipit ligula in', 10, 12, '2017-01-01 06:24:18', '2016-12-05 08:48:50', 51, 97, 18);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Bamity', 'condimentum id luctus nec molestie sed justo pellentesque viverra pede', 3, 15, '2016-12-16 14:54:51', '2017-05-17 22:52:46', 22, 30, 1);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tresom', NULL, 7, 8, '2017-06-14 15:18:57', '2016-12-02 16:10:21', 79, 5, 28);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Bytecard', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 4, 15, '2017-10-23 01:21:21', '2017-04-10 23:28:31', 20, 94, 14);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Konklux', 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', 10, 13, '2017-04-28 03:06:50', '2016-11-25 22:24:14', 48, 67, 17);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Fixflex', 'sit amet consectetuer adipiscing', 7, 14, '2017-05-30 04:08:35', '2017-01-14 18:34:55', 68, 38, 2);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Greenlam', 'et commodo vulputate justo in blandit ultrices enim lorem', 2, 13, '2017-06-07 05:01:08', '2017-11-16 20:39:02', 44, 75, 43);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Bitchip', 'neque aenean auctor gravida sem praesent', 6, 5, '2017-03-08 17:47:25', '2017-09-06 03:37:05', 62, 16, 24);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Holdlamis', 'orci luctus et ultrices posuere cubilia curae donec pharetra magna', 2, 8, '2017-03-31 21:29:59', '2017-02-08 16:01:24', 42, 45, 15);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Voyatouch', 'in lectus pellentesque at nulla suspendisse potenti cras', 6, 5, '2017-08-14 05:19:11', '2017-03-25 17:43:31', 37, 65, 10);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Latlux', 'habitasse platea dictumst morbi vestibulum velit id', 9, 4, '2017-08-29 09:44:32', '2017-01-10 22:33:38', 56, 35, 35);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zontrax', 'justo', 6, 7, '2017-09-11 05:04:48', '2017-09-07 14:28:45', 74, 24, 46);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Solarbreeze', 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede', 4, 7, '2017-04-12 07:26:07', '2017-03-07 03:44:19', 35, 19, 4);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Job', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', 9, 10, '2017-01-03 22:21:21', '2017-10-09 06:39:09', 63, 96, 49);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Job', 'semper porta volutpat quam pede lobortis ligula', 7, 14, '2017-05-17 13:25:39', '2016-12-11 18:35:58', 98, 52, 12);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Bitwolf', 'mi sit amet lobortis sapien', 5, 14, '2017-02-19 15:32:30', '2016-12-27 19:49:35', 96, 21, 47);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tres-Zap', 'viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', 6, 15, '2017-10-26 10:39:28', '2017-06-27 14:07:26', 92, 50, 25);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Sonair', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 9, 12, '2017-09-08 07:58:46', '2017-03-28 19:35:27', 28, 52, 28);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Opela', 'praesent', 2, 9, '2017-04-25 01:21:21', '2017-07-21 14:35:56', 84, 1, 50);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Alphazap', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 7, 6, '2017-09-10 14:25:25', '2017-03-19 14:46:35', 93, 14, 16);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Duobam', 'justo etiam pretium iaculis justo in hac habitasse platea', 8, 14, '2017-05-01 13:30:46', '2017-02-06 00:24:52', 43, 72, 21);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Alpha', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 4, 5, '2017-07-04 18:47:43', '2017-01-12 14:32:34', 80, 94, 49);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Prodder', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac', 6, 10, '2017-06-03 09:01:56', '2017-04-03 23:33:01', 100, 25, 40);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Latlux', NULL, 5, 15, '2017-02-27 14:12:54', '2017-02-25 06:41:37', 24, 3, 19);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Ronstring', 'sed tincidunt eu felis fusce posuere felis sed', 10, 6, '2017-01-11 22:49:14', '2016-12-26 21:19:20', 51, 89, 21);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Sub-Ex', 'vel ipsum praesent blandit', 1, 13, '2017-01-12 07:19:13', '2017-11-10 07:39:51', 21, 97, 26);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Wrapsafe', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 2, 14, '2017-10-06 10:44:07', '2017-11-15 18:40:36', 23, 17, 47);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Y-Solowarm', 'posuere', 4, 9, '2017-01-03 13:37:29', '2017-06-09 05:00:39', 38, 81, 7);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Alphazap', 'duis mattis egestas metus', 8, 9, '2017-09-25 10:52:06', '2017-01-28 18:56:33', 91, 54, 42);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Duobam', 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 6, 9, '2017-10-05 06:51:24', '2017-05-27 04:56:29', 30, 56, 44);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Duobam', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in', 10, 2, '2017-10-12 07:47:04', '2017-08-18 23:13:06', 77, 46, 1);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Veribet', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien', 3, 13, '2017-09-21 12:09:22', '2017-10-14 07:48:11', 57, 31, 34);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Keylex', 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', 5, 9, '2017-01-09 17:45:00', '2016-12-11 15:53:21', 89, 20, 3);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Trippledex', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin', 10, 11, '2017-11-10 13:35:27', '2017-08-15 22:30:09', 78, 83, 45);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Sonair', 'in hac', 2, 4, '2017-03-31 03:10:08', '2016-12-23 10:32:44', 28, 44, 21);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Temp', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', 7, 13, '2017-05-01 09:47:00', '2017-02-28 20:14:05', 17, 66, 4);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Opela', 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend', 1, 13, '2016-12-11 22:26:50', '2017-07-05 14:40:03', 89, 69, 16);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Subin', 'mi pede', 2, 11, '2017-01-21 22:07:37', '2017-07-02 18:56:22', 43, 19, 7);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Y-find', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris', 10, 9, '2017-08-22 16:31:58', '2017-03-25 07:34:54', 54, 22, 17);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tempsoft', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a', 10, 6, '2017-07-21 03:32:31', '2017-01-10 15:24:55', 25, 1, 8);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Andalax', NULL, 1, 7, '2017-03-19 16:57:17', '2017-09-11 13:52:53', 31, 86, 18);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Domainer', NULL, 5, 6, '2017-09-03 22:32:05', '2017-09-05 10:21:54', 7, 37, 11);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zontrax', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', 3, 5, '2017-01-28 09:16:49', '2017-06-19 20:38:07', 98, 70, 10);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Ventosanzap', 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 3, 4, '2017-04-11 14:53:42', '2017-02-13 07:33:12', 73, 14, 9);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tampflex', 'a nibh in quis justo', 9, 4, '2017-10-09 04:06:09', '2017-08-29 04:13:25', 54, 69, 29);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Overhold', 'et commodo vulputate justo in blandit ultrices', 8, 4, '2016-12-08 10:17:32', '2017-01-26 09:41:31', 100, 21, 8);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Regrant', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 6, 15, '2017-09-10 03:09:44', '2017-06-07 16:36:33', 55, 50, 32);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Fixflex', 'erat fermentum justo nec condimentum neque', 8, 5, '2017-06-09 18:25:48', '2017-08-04 13:57:14', 58, 18, 41);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Regrant', 'vel nisl duis ac', 10, 15, '2017-04-15 13:07:42', '2017-01-19 20:33:36', 29, 68, 33);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Treeflex', 'lectus pellentesque at nulla suspendisse', 2, 9, '2017-03-31 15:28:26', '2017-03-19 09:23:04', 26, 9, 38);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Matsoft', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 9, 3, '2017-11-09 10:42:51', '2017-08-02 02:03:42', 31, 11, 13);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zaam-Dox', 'mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 10, 9, '2017-11-11 09:48:03', '2017-05-12 23:00:57', 8, 66, 18);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tin', 'libero quis orci nullam molestie', 7, 9, '2017-03-10 05:44:42', '2017-05-18 05:47:08', 74, 4, 26);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Redhold', 'augue aliquam', 4, 13, '2017-08-09 07:32:21', '2017-08-05 04:18:49', 80, 57, 13);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Hatity', 'interdum venenatis turpis enim', 8, 3, '2017-07-19 04:13:26', '2017-01-18 21:00:46', 54, 60, 28);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Flexidy', 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 2, 2, '2017-11-12 05:10:52', '2017-07-07 20:58:54', 34, 50, 6);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Greenlam', 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 1, 6, '2017-10-22 11:33:37', '2016-12-01 20:38:11', 87, 21, 24);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Subin', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', 4, 5, '2017-06-20 14:31:38', '2017-07-17 18:41:56', 13, 59, 45);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zathin', 'at lorem integer tincidunt', 7, 11, '2016-11-23 05:46:25', '2017-11-13 22:20:52', 16, 25, 15);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Cookley', 'faucibus accumsan odio curabitur convallis', 3, 5, '2017-03-10 19:01:52', '2017-04-01 01:00:49', 22, 32, 34);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Biodex', 'hac habitasse platea dictumst morbi vestibulum velit', 1, 3, '2016-11-29 18:00:44', '2017-09-22 12:19:58', 28, 44, 30);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Treeflex', 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 2, 6, '2017-02-07 19:54:05', '2017-03-09 12:39:23', 8, 62, 31);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Zaam-Dox', 'tempus', 3, 9, '2017-10-07 12:43:12', '2017-02-12 12:21:54', 91, 66, 10);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Span', 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 6, 4, '2017-03-19 09:08:23', '2017-01-29 20:09:41', 25, 65, 45);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tin', 'posuere felis sed lacus morbi', 5, 4, '2017-09-14 15:00:17', '2017-07-02 02:55:50', 25, 28, 35);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Voyatouch', 'odio porttitor id consequat in consequat ut nulla sed', 9, 14, '2017-05-06 15:23:29', '2017-07-23 12:28:23', 87, 34, 50);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Andalax', 'sed ante vivamus tortor duis mattis egestas', 10, 8, '2017-08-28 21:28:07', '2017-05-16 01:23:44', 94, 81, 24);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Cardguard', 'ut blandit non interdum in ante', 8, 14, '2017-01-04 07:16:31', '2016-12-27 04:47:06', 59, 58, 10);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Pannier', 'integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 6, 15, '2017-05-24 01:20:22', '2016-11-26 18:08:44', 13, 62, 22);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tampflex', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', 4, 14, '2017-06-05 19:01:44', '2017-08-06 10:35:57', 12, 82, 14);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Duobam', 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', 9, 3, '2017-06-17 04:19:40', '2017-06-20 21:46:12', 48, 34, 36);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Ventosanzap', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 3, 11, '2017-04-19 05:33:45', '2017-01-01 12:28:23', 40, 11, 8);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Duobam', 'nulla', 5, 9, '2016-12-28 07:11:59', '2017-04-09 02:43:11', 47, 87, 1);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Cookley', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a', 6, 8, '2017-10-14 13:47:37', '2017-05-13 23:37:13', 79, 73, 7);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Opela', 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus', 1, 13, '2017-07-04 02:58:24', '2017-03-13 09:23:56', 63, 90, 35);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Stringtough', 'ut dolor morbi vel lectus in quam fringilla', 6, 14, '2017-07-13 00:23:40', '2017-08-22 00:01:32', 87, 41, 39);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Tin', 'id luctus nec molestie sed justo pellentesque', 6, 7, '2016-12-05 21:50:21', '2017-08-11 10:50:26', 89, 62, 46);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Sub-Ex', 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', 2, 2, '2017-03-20 10:33:14', '2017-08-04 22:06:06', 33, 7, 48);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Temp', 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum', 2, 2, '2017-01-06 17:54:25', '2017-06-16 10:35:07', 95, 76, 3);
INSERT INTO meeting (meetingName, meetingDesc, category, maxMembers, meetingDateTime, meetingCreated, locMeeting, locCreated, meetingOwner) VALUES ('Pannier', 'ultricies eu nibh quisque id justo', 9, 7, '2017-04-07 20:17:06', '2017-09-10 10:36:48', 59, 13, 14);

-- --------
-- MEETS --
-- --------

INSERT INTO meet (idMember, idMeeting) VALUES (31, 85);
INSERT INTO meet (idMember, idMeeting) VALUES (17, 88);
INSERT INTO meet (idMember, idMeeting) VALUES (44, 18);
INSERT INTO meet (idMember, idMeeting) VALUES (44, 62);
INSERT INTO meet (idMember, idMeeting) VALUES (44, 7);
INSERT INTO meet (idMember, idMeeting) VALUES (37, 40);
INSERT INTO meet (idMember, idMeeting) VALUES (25, 58);
INSERT INTO meet (idMember, idMeeting) VALUES (25, 70);
INSERT INTO meet (idMember, idMeeting) VALUES (14, 75);
INSERT INTO meet (idMember, idMeeting) VALUES (16, 17);
INSERT INTO meet (idMember, idMeeting) VALUES (18, 38);
INSERT INTO meet (idMember, idMeeting) VALUES (44, 84);
INSERT INTO meet (idMember, idMeeting) VALUES (45, 83);
INSERT INTO meet (idMember, idMeeting) VALUES (10, 67);
INSERT INTO meet (idMember, idMeeting) VALUES (5, 51);
INSERT INTO meet (idMember, idMeeting) VALUES (34, 52);
INSERT INTO meet (idMember, idMeeting) VALUES (16, 42);
INSERT INTO meet (idMember, idMeeting) VALUES (23, 78);
INSERT INTO meet (idMember, idMeeting) VALUES (38, 16);
INSERT INTO meet (idMember, idMeeting) VALUES (42, 39);
INSERT INTO meet (idMember, idMeeting) VALUES (26, 7);
INSERT INTO meet (idMember, idMeeting) VALUES (10, 21);
INSERT INTO meet (idMember, idMeeting) VALUES (44, 9);
INSERT INTO meet (idMember, idMeeting) VALUES (45, 93);
INSERT INTO meet (idMember, idMeeting) VALUES (2, 67);
INSERT INTO meet (idMember, idMeeting) VALUES (13, 86);
INSERT INTO meet (idMember, idMeeting) VALUES (17, 34);
INSERT INTO meet (idMember, idMeeting) VALUES (46, 26);
INSERT INTO meet (idMember, idMeeting) VALUES (9, 26);
INSERT INTO meet (idMember, idMeeting) VALUES (24, 95);
INSERT INTO meet (idMember, idMeeting) VALUES (38, 48);
INSERT INTO meet (idMember, idMeeting) VALUES (33, 77);
INSERT INTO meet (idMember, idMeeting) VALUES (50, 5);
INSERT INTO meet (idMember, idMeeting) VALUES (40, 100);
INSERT INTO meet (idMember, idMeeting) VALUES (34, 13);
INSERT INTO meet (idMember, idMeeting) VALUES (32, 24);
INSERT INTO meet (idMember, idMeeting) VALUES (44, 6);
INSERT INTO meet (idMember, idMeeting) VALUES (42, 40);
INSERT INTO meet (idMember, idMeeting) VALUES (43, 86);
INSERT INTO meet (idMember, idMeeting) VALUES (37, 59);
INSERT INTO meet (idMember, idMeeting) VALUES (36, 8);
INSERT INTO meet (idMember, idMeeting) VALUES (7, 51);
INSERT INTO meet (idMember, idMeeting) VALUES (39, 11);
INSERT INTO meet (idMember, idMeeting) VALUES (45, 61);
INSERT INTO meet (idMember, idMeeting) VALUES (15, 34);
INSERT INTO meet (idMember, idMeeting) VALUES (28, 91);
INSERT INTO meet (idMember, idMeeting) VALUES (33, 5);
INSERT INTO meet (idMember, idMeeting) VALUES (49, 70);
INSERT INTO meet (idMember, idMeeting) VALUES (4, 42);
INSERT INTO meet (idMember, idMeeting) VALUES (13, 66);
INSERT INTO meet (idMember, idMeeting) VALUES (18, 80);
INSERT INTO meet (idMember, idMeeting) VALUES (23, 69);
INSERT INTO meet (idMember, idMeeting) VALUES (45, 48);
INSERT INTO meet (idMember, idMeeting) VALUES (38, 22);
INSERT INTO meet (idMember, idMeeting) VALUES (18, 71);
INSERT INTO meet (idMember, idMeeting) VALUES (20, 5);
INSERT INTO meet (idMember, idMeeting) VALUES (26, 79);
INSERT INTO meet (idMember, idMeeting) VALUES (41, 44);
INSERT INTO meet (idMember, idMeeting) VALUES (47, 96);
INSERT INTO meet (idMember, idMeeting) VALUES (15, 43);
INSERT INTO meet (idMember, idMeeting) VALUES (32, 38);
INSERT INTO meet (idMember, idMeeting) VALUES (4, 80);
INSERT INTO meet (idMember, idMeeting) VALUES (35, 64);
INSERT INTO meet (idMember, idMeeting) VALUES (5, 19);
INSERT INTO meet (idMember, idMeeting) VALUES (36, 49);
INSERT INTO meet (idMember, idMeeting) VALUES (15, 78);
INSERT INTO meet (idMember, idMeeting) VALUES (8, 68);
INSERT INTO meet (idMember, idMeeting) VALUES (35, 90);
INSERT INTO meet (idMember, idMeeting) VALUES (23, 91);
INSERT INTO meet (idMember, idMeeting) VALUES (25, 13);

