insert into location (postalCode, locName) values (82887, 'Badin');
insert into location (postalCode, locName) values (28254, 'Cau Giay');
insert into location (postalCode, locName) values (18105, 'Batelov');
insert into location (postalCode, locName) values (24186, 'Tallbisah');
insert into location (postalCode, locName) values (29781, 'Buenavista');
insert into location (postalCode, locName) values (71637, 'Laylay');
insert into location (postalCode, locName) values (95468, 'Gorki');
insert into location (postalCode, locName) values (65344, 'Jiachuan');
insert into location (postalCode, locName) values (61535, 'Ngurensiti');
insert into location (postalCode, locName) values (78546, 'Tertek');
insert into location (postalCode, locName) values (88852, 'Sirnasari');
insert into location (postalCode, locName) values (54326, 'Tungelsta');
insert into location (postalCode, locName) values (25855, 'San Jose de las Lajas');
insert into location (postalCode, locName) values (95589, 'Kuripan');
insert into location (postalCode, locName) values (30569, 'Hekou');
insert into location (postalCode, locName) values (17350, 'Yuli');
insert into location (postalCode, locName) values (62378, 'Norberg');
insert into location (postalCode, locName) values (72819, 'Nizhniye Vyazovyye');
insert into location (postalCode, locName) values (44360, 'Abiko');
insert into location (postalCode, locName) values (57913, 'Lamawan');
insert into location (postalCode, locName) values (73641, 'Norrköping');
insert into location (postalCode, locName) values (92858, 'Sanxiang');
insert into location (postalCode, locName) values (68914, 'Jedlnia-Letnisko');
insert into location (postalCode, locName) values (93680, 'Aix-en-Provence');
insert into location (postalCode, locName) values (41801, 'Ramenki');
insert into location (postalCode, locName) values (89114, 'Rivera');
insert into location (postalCode, locName) values (43255, 'Futian');
insert into location (postalCode, locName) values (60502, 'Renfengzhuang');
insert into location (postalCode, locName) values (28373, 'Qiying');
insert into location (postalCode, locName) values (73213, 'Fushe-Bulqize');
insert into location (postalCode, locName) values (78669, 'Rantau');
insert into location (postalCode, locName) values (79580, 'Al Humaydat');
insert into location (postalCode, locName) values (11044, 'San Francisco');
insert into location (postalCode, locName) values (46332, 'Pamiers');
insert into location (postalCode, locName) values (25425, 'Guanghai');
insert into location (postalCode, locName) values (80278, 'Örebro');
insert into location (postalCode, locName) values (53333, 'Paris 14');
insert into location (postalCode, locName) values (41538, 'Facatativa');
insert into location (postalCode, locName) values (71298, 'Grabow nad Prosna');
insert into location (postalCode, locName) values (79541, 'Storvik');
insert into location (postalCode, locName) values (52527, 'Governador Valadares');
insert into location (postalCode, locName) values (69361, 'Sagae');
insert into location (postalCode, locName) values (20614, 'Jiuhua');
insert into location (postalCode, locName) values (24087, 'Bogo');
insert into location (postalCode, locName) values (57954, 'Shache');
insert into location (postalCode, locName) values (79112, 'Hellevoetsluis');
insert into location (postalCode, locName) values (37843, 'Zhulebino');
insert into location (postalCode, locName) values (21835, 'Gnosjö');
insert into location (postalCode, locName) values (70162, 'Lam Thao');
insert into location (postalCode, locName) values (33186, 'Cheongsong gun');
insert into location (postalCode, locName) values (85457, 'Cikandang');
insert into location (postalCode, locName) values (77075, 'Doug An');
insert into location (postalCode, locName) values (81985, 'Timezgadiouine');
insert into location (postalCode, locName) values (94946, 'Dayton');
insert into location (postalCode, locName) values (93051, 'Ban Lam Luk Ka');
insert into location (postalCode, locName) values (79149, 'Banjar Dharmasemedi');
insert into location (postalCode, locName) values (82751, 'Maloarkhangelsk');
insert into location (postalCode, locName) values (95215, 'Vyatskiye Polyany');
insert into location (postalCode, locName) values (93274, 'Lexington');
insert into location (postalCode, locName) values (18336, 'Nürnberg');
insert into location (postalCode, locName) values (26370, 'Mayong');
insert into location (postalCode, locName) values (54251, 'Lewograran');
insert into location (postalCode, locName) values (69753, 'Ipora');
insert into location (postalCode, locName) values (11121, 'Nar-yan-Mar');
insert into location (postalCode, locName) values (86001, 'Getazat');
insert into location (postalCode, locName) values (41438, 'Nicolas Bravo');
insert into location (postalCode, locName) values (66403, 'Hejiabao');
insert into location (postalCode, locName) values (63850, 'Lusaka');
insert into location (postalCode, locName) values (33309, 'Tamboril');
insert into location (postalCode, locName) values (64447, 'Si Mahosot');
insert into location (postalCode, locName) values (57330, 'Qiling');
insert into location (postalCode, locName) values (25771, 'Lobanovo');
insert into location (postalCode, locName) values (98213, 'Brumado');
insert into location (postalCode, locName) values (92419, 'Krajanbonjor');
insert into location (postalCode, locName) values (33586, 'Gorzow Slaski');
insert into location (postalCode, locName) values (87157, 'Leuweheq');
insert into location (postalCode, locName) values (86611, 'Kampungruweh');
insert into location (postalCode, locName) values (65080, 'Tsotsin-Yurt');
insert into location (postalCode, locName) values (69697, 'Heichengzi');
insert into location (postalCode, locName) values (76613, 'Jiulong');
insert into location (postalCode, locName) values (85536, 'Campos Belos');
insert into location (postalCode, locName) values (11646, 'Iecava');
insert into location (postalCode, locName) values (60261, 'Ostrov');
insert into location (postalCode, locName) values (81727, 'Bom Jesus do Itabapoana');
insert into location (postalCode, locName) values (13882, 'Long’an Chengxiangzhen');
insert into location (postalCode, locName) values (22398, 'Uubulan');
insert into location (postalCode, locName) values (79235, 'Ismayilli');
insert into location (postalCode, locName) values (68001, 'Poniatowa');
insert into location (postalCode, locName) values (72192, 'Xiuyu');
insert into location (postalCode, locName) values (52147, 'Västeras');
insert into location (postalCode, locName) values (42770, 'Muhambal');
insert into location (postalCode, locName) values (42355, 'Esigodini');
insert into location (postalCode, locName) values (44408, 'Jiaokou');
insert into location (postalCode, locName) values (89998, 'San Jose');
insert into location (postalCode, locName) values (16621, 'Qingyang');
insert into location (postalCode, locName) values (78884, 'Cabucgayan');
insert into location (postalCode, locName) values (62969, 'Amnat Charoen');
insert into location (postalCode, locName) values (20569, 'Hluboka nad Vltavou');
insert into location (postalCode, locName) values (12672, 'San Pedro Apartado');
insert into location (postalCode, locName) values (72184, 'Yuannan');
